### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dsyme** [SAFE-Stack/SAFE-ConfPlanner#27]
I was taking a look at this sample. A couple of things

1. I had to uninstall Windows HPC 2012 client pack from Windows because of [node.exe from node.js conflicts node.exe from Microsoft HPC Pack](https://github.com/nodejs/node-v0.x-archive/issues/7773) 

2. I got this error, not sure if it's critical or not

![image](https://user-images.githubusercontent.com/7204669/32740774-e2b8049a-c89b-11e7-967f-4503b6d8df1b.png)

**Comment by dsyme** [comment]
Also this error

![image](https://user-images.githubusercontent.com/7204669/32742656-03af8de8-c8a2-11e7-9feb-7d3d3902f815.png)

**Comment by rommsen** [comment]
Hey Don

Thanks for chipping in. Both errors a basically the same (because there is an event store for the conference page as well as one for the dummy page). It tries to open an event store file which is not there yet but it should be working anyway.

The stack trace is printed because I left a [printfn in the code](https://github.com/rommsen/ConfPlanner/blob/master/src/Infrastructure/EventStore.fs#L47)

Btw. the second error goes away when you run `build.cmd RunFixtures`. This will prefill the conference event store with some fixture data and make the conference example usable (and it might even include a proposed abstract from you 😄 )

Regards

**Comment by dsyme** [comment]
Thanks, I didn't read as far as `build.cmd RunFixtures`

**Comment by rommsen** [comment]
Clean up
