### ISSUE TITLE
Uncaught JS error: Cannot deserialize into Global.UserData

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-ConfPlanner#54]
I tried to fiddle with the app locally:

1. cloned git repo
2. `build runfixture`
3. `build run`

Both build steps seem to succeed, app starts but I get following error in Chrome console:

```
Uncaught Error: Cannot deserialize into Global.UserData - Error (inflate): undefined (OrganizerId) is not of type Domain.Model.OrganizerId - Data: '{"UserName":"test","Token":"{token_here}"}'
    at raise (State.fs:307)
    at ofJson (State.fs:321)
    at State.fs:8
    at defaultArg (State.fs:44)
    at loadUser (State.fs:8)
    at init (State.fs:63)
    at Program.init (App.fs:12)
    at Program.init (navigation.fs:88)
    at App.fs:53
    at Program.init (App.fs:53)
```

This happens at init so nothing is displayed

**Comment by rommsen** [comment]
The problem is that the deserialization of the stuff stored in local storage is not working. I guess either you have run an older version of ConfPlanner or another app that runs on localhost:8080 and stores its stuff in local storage under the key "user" (e.g. SAFE Bookstore). For now, can you delete everything in local storage under the key user? I will change the key to something less generic after new year is over :D

**Comment by theimowski** [comment]
Thanks, removing the data under "user" key from local storage did the job
