### ISSUE TITLE
Missing conference_eventstore.json

### ISSUE THREAD

**Issue by srlopez** [SAFE-Stack/SAFE-ConfPlanner#63]
Trying to running Support app
```
open Infrastructure.EventStore
open Support

let readEvents,appendEvents =
  eventStore @"..\Server\conference_eventstore.json"

[<EntryPoint>]
let main _ =
  [Conference1.eventSets(); Conference2.eventSets()]
  |> List.concat
  |> List.map (fun eventSet -> async { do! appendEvents eventSet})
  |> List.iter Async.RunSynchronously
  |> ignore

  0
```
i think is missing file `conference_eventstore.json` on Server folder

**Comment by rommsen** [comment]
Hi there,

thanks for the comment. You can just create an empty file at the given location.

Btw: I have not updated the repo for quite some time to work with current netcore versions (planning a rewrite for quite some time now). Not sure if everything will work as expected.

**Comment by coodoo** [comment]
@rommsen  Hey Roman, any plan to have this great example rewritten soon? Really want to have it compile and run on my Mac so that I could learn your approach, thanks!

Btw, I installed the old version of dotnet sdk as specified in `global.json` but still failed to dump the demo data, hence rendered the code un-executable.

**Comment by rommsen** [comment]
Hey everyone. I have rewritten a lot of the backend stuff. It uses now an in memory event store implementation, so no fixtures needed. Every server restart will put the event store in its initial state.
